-include /etc/os-release
ARCH=		$(shell uname -m)

PG_VERSION?=	16
PG_CONFIG?=	/usr/pgsql-${PG_VERSION}/bin/pg_config

ifeq ($ID), "centos")
ifeq ($VERSION_ID), "7")
PG_VERSION=15
endif
endif

ifeq ($(ID), debian)
PG_CONFIG=/usr/bin/pg_config
endif

ifeq ($(ID), fedora)

ifeq ($(ARCH), aarch64)
PG_CONFIG=	/usr/bin/pg_config
endif

ifeq ($(VERSION_ID), "39")
PG_VERSION=15
endif

ifeq ($(VERSION_ID), "38")
PG_VERSION=15
endif

endif
