.\" Copyright (c) 2023 - 2024 Marc Balmer HB9SSB
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to
.\" deal in the Software without restriction, including without limitation the
.\" rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
.\" sell copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
.\" IN THE SOFTWARE.
.\"
.TH TRX-CONTROL 7 "5 October 2024" "trx-control"
.SH NAME
trx-control \- software to control amateur radio transceivers
.SH DESCRIPTION
.
Software to control amateur radio transceivers and related hardware like
relays, GPIO pins, rotators.
.
.PP
trx-control consists of
.IR trxd (8)
(a daemon to control the transceivers and other hardware) and
.IR trxctl (1)
a command line utility to access trxd.
.PP
Software that wants to make use of
.IR trxd (8)
should implement the protocol and talk to
.IR trxd (8)
directly over the network.
.
.
.PP
.IR trxd (8)
listens on port 14285 by default for incoming connections over
plain sockets and can optionally listen for WebSocket connections.

It supports both IPv4 and IPv6.
.
.PP
The effective transceiver control is done using Lua modules,
this way new transceivers can easily be supported by supplying
a corresponding Lua driver module for a specific transceiver model.
See https://lua.org and https://lua.msys.ch for more information on Lua.
.
.
.SH FILES
.
.TP
.I /usr/bin/trxctl
trx-control client.
.
.
.TP
.I /usr/sbin/trxd
trx-control daemon.
.
.
.TP
.I /usr/share/trxd/protocol
Lua scripts that implement common transceiver control protocols.
These can be used by the actual drivers.
.
.
.TP
.I /usr/share/trxd/trx
Lua scripts that control transceivers.
.
.
.TP
.I /usr/share/trxd/gpio
Lua scripts that control GPIO devices.
.
.
.TP
.I /usr/share/trxd/extension
Lua scripts that extend trx-control in a generic way.
.
.
.TP
.I /usr/share/trxd/lua
Lua modules for use by extensions.
.
.
.SH AUTHORS
.
The trx-control software was written by
.MT qsl\@hb9ssb.radio
Marc Balmer HB9SSB
.ME .
.
.
.SH "SEE ALSO"
.
.PP
.IR bluecat (1) ,
.IR trxctl (1) ,
.IR trxd (8)
.PP
The client/server protocol is documented in the projects website at
https://trx-control.msys.ch.
.
.
