.\" Copyright (c) 2023 Marc Balmer HB9SSB
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to
.\" deal in the Software without restriction, including without limitation the
.\" rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
.\" sell copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
.\" IN THE SOFTWARE.
.\"
.TH TRX-CONTROL 7 "15 September 2023" "trx-control"
.SH NAME
trx-control \- software to control radio transceivers
.SH DESCRIPTION
.
Software to control amateur radio transceivers.
.
.PP
trx-control consists of
.IR trxd (8)
(a daemon to control the transceivers), and,
.IR trxctl (1)
(a command line utility to access trxd.)
.PP
.IR trxctl (1)
is meant as a reference client only.
Software that wants to make use of
.IR trxd (8)
should implement the protocol and talk to
.IR trxd (8)
directly over the network.
.
.
.PP
.IR trxd (8)
listens on port 14285 by for incoming connections
(14285 is the default port, it can be changed).
It supports both IPv4 and IPv6.
.
.PP
The effective transceiver control is done using Lua modules,
this way new transceivers can easily be supported by suppliying
a corresponding Lua module for a specific transceiver model.
See https://lua.org and https://lua.msys.ch for more information on Lua.
.
.
.SH "SUPPORTED TRANSCEIVERS"
.PP
Initially, trx-control will support the following transceivers:
.
.PP
.TS
l l l.
Manufacturor	Model	Driver	CAT Bit Rate
.T&
l l l.
_
Yaesu	FT-710	yaesu-ft-710	38400
Yaesu	FT-897	yaesu-ft-897	38400
Yaesu	FT-817	yaesu-ft-817	38400
Yaesu	FT_991A	yaesu-ft-991a	38400
.TE
.
Make sure to set the CAT bit rate to the value expected by
.IR trxd (8) .
.
.
.SH FILES
.
.TP
.I /usr/bin/trxctl
trx-control client.
.
.
.TP
.I /usr/sbin/trxd
trx-control daemon.
.
.
.TP
.I /usr/share/trxd/trx
Lua scripts that control transceivers.
.
.
.SH AUTHORS
.
The trx-control software was written by
.MT marc\@msys.ch
Marc Balmer HB9SSB
.ME .
.
.
.SH "SEE ALSO"
.
.PP
.IR trxctl (1),
.IR trxd (8)
.PP
The client/server protocol is documented in the projects wiki at
https://github.com/hb9ssb/trx-control/wiki.
.
.
