ARCH!=		arch

REPOPATH=	/var/apks/$(ARCH)

LICENSE?=	custom
PACKAGER?=	unknown
DESCRIPTION?=	unknown
PACKAGER?=	unknown
URL?=		unknown
MAINTAINER?=	unknown
INSTSCRIPTS!=	find . -name .p\*-\*install -exec basename {} \;
DATE_EPOCH!=	date -u "+%s"

.DEFAULT_GOAL=	package

package:
# Create the data part
	@-mkdir -p staging ${REPOPATH}
	@tar -C /tmp/alpine -f - -c ${FILES} | tar -C staging -x

	@find staging -exec touch -h -d @${DATE_EPOCH} {} +

	@(cd staging; tar --xattrs -f - -c *) | abuild-tar --hash | \
		gzip > data.tar.gz

# This is how it is done in abuild:
#(cd staging; find . -print0) | LC_ALL=C sort -z | tar -C staging --xattrs \
#		--xattrs-exclude=security.selinux \
#		--format=posix \
#		--pax-option=exthdr.name=%d/PaxHeaders/%f,atime:=0,ctime:=0 \
#		--mtime="@${DATE_EPOCH}" \
#		--no-recursion --null -T - \
#		-f - -c | abuild-tar --hash | gzip -n -9 >data.tar.gz

# Create .PKGINFO
	@echo "# Generated by alpine.package.mk" > .PKGINFO
	@echo -n "# " >> .PKGINFO
	@date >> .PKGINFO
	@echo "pkgname = ${PACKAGE}" >> .PKGINFO
	@echo "pkgver = ${PKGVER}" >> .PKGINFO
	@echo "pkgdesc = ${DESCRIPTION}" >> .PKGINFO
	@echo "url = ${URL}" >> .PKGINFO
	@echo "builddate = ${DATE_EPOCH}" >> .PKGINFO
	@echo "commit = 5ff2c19564c162690aa5abbfb46fd6d3960c1c24" >> .PKGINFO
	@echo "packager = ${PACKAGER}" >> .PKGINFO
	@echo -n "size = " >> .PKGINFO
	@(cd staging; du -b -c ${FILES}) | tail -n 1 | cut -f 1 >> .PKGINFO
	@echo "arch = ${ARCH}" >> .PKGINFO
	@echo "origin = ${PACKAGE}" >> .PKGINFO
	@echo "maintainer = ${MAINTAINER}" >> .PKGINFO
	@echo "license = ${LICENSE}" >> .PKGINFO
	@for dep in ${DEPENDS}; do echo "depend = $${dep}" >> .PKGINFO; done
	@echo "# automatically detected:" >> .PKGINFO
	@for f in ${BINARIES}; \
	do \
		find /tmp/alpine -name $${f} -type f -perm -111; \
		echo -n "provides = cmd:" >> .PKGINFO; \
		basename $${f}  >> .PKGINFO; \
#		basename $${f} | tr -d '\n' >> .PKGINFO; \
#		echo "=${PKGVER}" >> .PKGINFO; \
	done
	echo -n "datahash = " >>.PKGINFO
	sha256sum data.tar.gz | cut -d " " -f 1 >> .PKGINFO
	@echo ====
	@cat .PKGINFO
	@echo ====

# Create the control part (index)
	@tar --format=posix \
		--pax-option=exthdr.name=%d/PaxHeaders/%f,atime:=0,ctime:=0 \
		--mtime="@${DATE_EPOCH}" \
		-f - -c .PKGINFO ${INSTSCRIPTS} | abuild-tar --cut \
		| gzip -n -9 > control.tar.gz


#@tar --owner=0 --group=0 --numeric-owner -c .PKGINFO ${INSTSCRIPTS} | \
#	abuild-tar --cut | gzip > control.tar.gz
	abuild-sign -q control.tar.gz

# Produce the final apk
	cat control.tar.gz data.tar.gz > ${REPOPATH}/${PACKAGE}-${PKGVER}.apk

# Clean up
	@rm -rf data.tar.gz control.tar.gz .PKGINFO staging
