.\" Copyright (c) 2023 Marc Balmer HB9SSB
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to
.\" deal in the Software without restriction, including without limitation the
.\" rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
.\" sell copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
.\" IN THE SOFTWARE.
.\"
.TH TRXD 8 "12 September 2023" "trx-control"
.
.SH NAME
trxd
.
.
.SH SYNOPSIS
trxd [-dl] [-b address] [-p port] [-P path]
.
.
.SH DESCRIPTION
.
.IR trxd (8)
is a daemon to control amateur radio transceivers.
.IR trxd (8)
listens for incoming TCP/IP connections from trx-control compatible clients.
.
.
.SH OPTIONS
.
.TP
-b <address>
Set the bind (listen) address.
If unspecified, "localhost" is used.
.TP
-d
Do not daemonize (run in foreground).
.TP
-l
Log connection attempts.
.TP
-p <port>
Set the listen port.
If unspecified
.IR trxd (8)
uses port 14285.
.TP
-P <path>
Set the path name of a pid file.
.
.
.SH "SUPPORTED TRANSCEIVERS"
.PP
Initially,
.IR trxd (8)
will support the following transceivers:
.
.PP
.TS
l l l.
Manufacturor	Model	Driver
.T&
l l l.
_
Yaesu	FT-710	yaesu-ft-710
Yaesu	FT-897	yaesu-ft-897
Yaesu	FT-817	yaesu-ft-817
.TE
.
.
.SH AUTHORS
.
The trx-control software was written by
.MT marc\@msys.ch
Marc Balmer HB9SSB
.ME .
.
.
.SH SEE ALSO
.
.PP
.IR trx-control (7),
.IR trxctl (1)
.
.
