.\" Copyright (c) 2023 - 2024 Marc Balmer HB9SSB
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to
.\" deal in the Software without restriction, including without limitation the
.\" rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
.\" sell copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
.\" IN THE SOFTWARE.
.\"
.TH TRXD 8 "1 January 2024" "trx-control"
.
.SH NAME
trxd
.
.
.SH SYNOPSIS
trxd [-dlvV] [-b address] [-c path] [-g group] [-p port] [-u user] [-P path]
.
.
.SH DESCRIPTION
.
.IR trxd (8)
is a daemon to control amateur radio transceivers.
.IR trxd (8)
listens for incoming TCP/IP connections from trx-control compatible clients.
.
.
.SH OPTIONS
.
.TP
-b <address>
Set the bind (listen) address.
If unspecified, "localhost" is used.
.TP
-c <path>
Set the path name of a configuration file if the default /etc/trxd.yaml is
not to be used.
.TP
-g <group>
Set the group under which
.IR trxd (8)
is to be run.
.TP
-u <user>
Set the user under which
.IR trxd (8)
is to be run.
.TP
-d
Do not daemonize (run in foreground).
.TP
-l
Log connection attempts.
.TP
-v
Increase verbosity.
.TP
-V
Show the version number and exit.
.TP
-p <port>
Set the listen port.
If unspecified
.IR trxd (8)
uses port 14285.
.TP
-P <path>
Set the path name of a pid file.
.
.
.SH "SUPPORTED TRANSCEIVERS"
.PP
.IR trxd (8)
supports the following transceivers:
.
.PP
.TS
l l l.
Manufacturor	Model	Driver
.T&
l l l.
_
ICOM	IC-705	icom-ic-705
Yaesu	FT-710	yaesu-ft-710
Yaesu	FT-891	yaesu-ft-891
Yaesu	FT-897	yaesu-ft-897
Yaesu	FT-817	yaesu-ft-817
Yaesu	FT-991a	yaesu-ft-991a
.TE
.
.
.SH "SUPPORTED GPIO DEVICES"
.PP
.TS
l l l.
Manufacturor	Model	Driver
.T&
l l l.
_
bmcm	USB-PIO	bmcm-usb-pio
bmcm	OR8	Attached to USB-PIO
.TE
.
.
.SH FILES
.
.TP
.I /etc/trxd.yaml
Default configuration file.
An example configuration file can be found in /usr/share/trxd/trxd.yaml.
.
.TP
.I /usr/share/trxd/trx-controller.lua
Upper part of the transceiver driver mechanism.
Do not edit this file.
.
.TP
.I /usr/share/trxd/protocol
Directory containing common protocols for transceiver control.
These can be used by the actual drivers.
.
.TP
.I /usr/share/trxd/trx
Directory containing the actual transceiver drivers.
New drivers must be added in this directory.
.
.TP
.I /usr/share/trxd/gpio
Directory containing the actual GPIO drivers.
New GPIO drivers must be added in this directory.

.
.TP
.I /usr/share/trxd/extension
Directory containing trxd extension scripts in Lua.
.
.TP
.I /usr/share/trxd/lua
Directory containg Lua modules for use by extensions.
.
.SH AUTHORS
.
The
.IR trxd (8)
daemon was written by
.MT marc\@msys.ch
Marc Balmer HB9SSB
.ME .
.
.
.SH SEE ALSO
.
.PP
.IR trx-control (7),
.IR trxctl (1) ,
.IR xqrg (1)
